[bc]
name="DirichletBC"
idof=1
nodalValueType="Constant" # Time, SpaceTime, Space
useFunction=false
isNormal=false
isTangent=false
useExternal=false
value=20.0 # when nodalValueType=Constant
# value=[1.0, 2.0, 3.0, 4.0] # when nodalValueType=Space
# value=[1.0, 2.0, 3.0, 4.0] # when nodalValueType=Time 
# value=[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0]] # SpaceTime
spaceFunction="lua script f(x)"
timeFunction="lua script f(t)"
spaceTimeFunction="lua script f(x, t)"

[bc.boundary]
isSelectionByMeshID = false
isSelectionByElemNum = false
isSelectionByBox = false
isSelectionByNodeNum = false 

[bc.boundary.meshID]
point = [1,2,3] # "filename.txt"
line = [1,2,3,4] # "filename.txt"
surface = [1,2,3] # "filename.txt"
volume = [1,2,3] # "filename.txt"

[bc.boundary.box]
point = [
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=0.0, zmax=1.0},
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=2.0, zmax=3.0}
]

line = [
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=0.0, zmax=1.0},
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=2.0, zmax=3.0}
]

surface = [
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=0.0, zmax=1.0},
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=2.0, zmax=3.0}
]

volume = [
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=0.0, zmax=1.0},
{xmin=0.0, xmax=1.0, ymin=0.0, ymax=1.0, zmin=2.0, zmax=3.0}
]

[bc.boundary.elemNum]
point = [1,2,3]
line = [1,2,3]
surface=[1,2,3]
volume=[1,2,3]

[bc.boundary.nodeNum]
point = [1,2,3]
line = [1,2,3]
surface=[1,2,3]
volume=[1,2,3]

